name: mm_tf_new
channels:
- conda-forge
dependencies:
- anyio
- appdirs
- appnope
- argon2-cffi
- argon2-cffi-bindings
- arrow
- asttokens
- async-lru
- attrs
- babel
- beautifulsoup4
- bleach
- brotli-python
- bzip2
- ca-certificates
- cached-property
- cached_property
- certifi
- cffi
- charset-normalizer
- click
- comm
- debugpy
- decorator
- defusedxml
- docker-pycreds
- entrypoints
- exceptiongroup
- executing
- fqdn
- gitdb
- gitpython
- h11
- h2
- hpack
- httpcore
- httpx
- hyperframe
- idna
- importlib-metadata
- importlib_metadata
- importlib_resources
- ipykernel
- ipython
- isoduration
- jedi
- jinja2
- json5
- jsonpointer
- jsonschema
- jsonschema-specifications
- jsonschema-with-format-nongpl
- jupyter-lsp
- jupyter_client
- jupyter_core
- jupyter_events
- jupyter_server
- jupyter_server_terminals
- jupyterlab
- jupyterlab_pygments
- jupyterlab_server
- libabseil
- libcxx
- libexpat
- libffi
- libprotobuf
- libsodium
- libsqlite
- libzlib
- markupsafe
- matplotlib-inline
- mistune
- nbclient
- nbconvert-core
- nbformat
- ncurses
- nest-asyncio
- notebook
- notebook-shim
- openssl
- overrides
- packaging
- pandocfilters
- parso
- pexpect
- pickleshare
- pip
- pkgutil-resolve-name
- platformdirs
- prometheus_client
- prompt-toolkit
- protobuf
- psutil
- ptyprocess
- pure_eval
- pycparser
- pygments
- pyobjc-core
- pyobjc-framework-cocoa
- pysocks
- python
- python-dateutil
- python-fastjsonschema
- python-json-logger
- python_abi
- pytz
- pyyaml
- pyzmq
- readline
- referencing
- requests
- rfc3339-validator
- rfc3986-validator
- rpds-py
- ruff
- send2trash
- sentry-sdk
- setproctitle
- setuptools
- six
- smmap
- sniffio
- soupsieve
- stack_data
- terminado
- tinycss2
- tk
- tomli
- tornado
- traitlets
- types-python-dateutil
- typing-extensions
- typing_extensions
- typing_utils
- tzdata
- uri-template
- urllib3
- wandb
- wcwidth
- webcolors
- webencodings
- websocket-client
- wheel
- xz
- yaml
- zeromq
- zipp

